language: minimal

services:
  - docker

script:
  - docker-compose run --rm mobile bash -c 'flutter test --coverage && pub global activate coveralls && $HOME/.pub-cache/bin/coveralls coverage/lcov.info'
